### ISSUE TITLE
Work plan for mono_lidar refactor

### ISSUE THREAD

**Issue by johannes-graeter** [johannes-graeter/limo#76]
# steps for preparation
* Write a main that reporduces complete process  with kitti data
  - [x] make reader for kitti data
  - [ ] add limo behaviour to that main (params can be read by ros)
  - [ ] evaluate on kitti to repodruce results
 
* Write more unit tests for expected current behaviour
* Identify in which mode monolidar ist currently launched

# things to make better
   * One coding style
   * No NULL
   * Remove unused options
   * Clear input and output
   * Output as return
   * Error state through return
   * Noexcept
   * Some double work could be reduced

# open questions
* Logger? 

   @zephyrdaddy
